# Generated by Django 5.1.4 on 2025-03-16 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
